### ISSUE TITLE
Remove `flex-grow` from `.col`

### ISSUE THREAD

**Issue by katydecorah** [mapbox/assembly#1016]
When using `grid` to build a `col` layout, if there are uneven number of items the last item will go full-width:

![image](https://user-images.githubusercontent.com/2180540/118858105-c4287600-b8a6-11eb-82db-f35de292b15e.png)
[Reduce test case](https://codepen.io/katydecorah/pen/4640926a8251b147692ec4d3374bd467?editors=1100)

This happens because `.col` sets `flex-grow: 1`. Since we have two options to allow items to grow `.col--auto` and `.flex-child-grow`, we should remove `flex-grow` from `.col`. 

With this change, it will change the concept of `.col` slightly since the class will depend on other to give its shape within the grid.

## Which classes benefit from flex-grow?

If we make this change, we lose the concept of the uncontrolled grid with the `.col` class. This means you will need to use a `.w-*` or `.col--auto` class to take advantage of the grid:

`.col` with `flex-grow` | `.col` without `flex-grow`
:---|:---
<img width="1098" alt="Screen Shot 2021-05-19 at 1 53 18 PM" src="https://user-images.githubusercontent.com/2180540/118860617-9db80a00-b8a9-11eb-8b02-e4d2d44a37c2.png"> | <img width="1098" alt="Screen Shot 2021-05-19 at 1 53 22 PM" src="https://user-images.githubusercontent.com/2180540/118860616-9d1f7380-b8a9-11eb-8a78-a7f65344f64c.png">

If we make this change, the %-based margins may need a `.w-*` or `.col--auto` class:

`.col` with `flex-grow` | `.col` without `flex-grow`
:---|:---
<img width="734" alt="Screen Shot 2021-05-19 at 1 44 36 PM" src="https://user-images.githubusercontent.com/2180540/118859616-6dbc3700-b8a8-11eb-8190-2d04c25ed677.png"> | <img width="734" alt="Screen Shot 2021-05-19 at 1 44 10 PM" src="https://user-images.githubusercontent.com/2180540/118859617-6e54cd80-b8a8-11eb-9ab2-2ce93ab840c5.png">

## What alternatives have you tried?

- Introduce a new class `flex-child-no-grow` that will disable `flex-grow`. This works, but adds code to Assembly.
- Use a right % margin on the last element. This solution works, but is a bit clunky and may not scale well.
- Removing `col` class from each element works, but then you cannot use `grid--gut*` classes to add spacing between elements.

**Comment by samanpwbb** [comment]
> If we make this change, we lose the concept of the uncontrolled grid with the `.col` class. This means you will need to use a `.w-*` or `.col--auto` class to take advantage of the grid:

I like this! Reducing the scope of individual classes makes Assembly more flexible. We can recommend using col in combination with flex-child-grow to get the old behavior!
