### ISSUE TITLE
Tooltip styles

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#144]
Do we want component classes for tooltips?

**Comment by tristen** [comment]
The basic one is in place here: https://www.mapbox.com/assembly/examples/tooltips/

We should include alternate arrow directions and possibly a popover style?

**Comment by samanpwbb** [comment]
Examples for tooltips pointing in all 4 directions would be good 👍

**Comment by mayagao** [comment]
![screen shot 2017-01-18 at 11 40 56 am](https://cloud.githubusercontent.com/assets/5186564/22073311/0733830e-dd73-11e6-8380-8a9b9847152d.png)

can we add a rounded corner to the bottom triangle?

**Comment by samanpwbb** [comment]
> can we add a rounded corner to the bottom triangle?

We could round the bottom triangle only if we used an image instead of CSS to make the triangle. 

I suppose rounded triangles in the spirit of assembly (easy to recolor and reuse) _would_ be possible with SVG. Maybe make a separate issue about this?

**Comment by samanpwbb** [comment]
🤔  You could do this with css transform, a rotated square with rounded corners, and overflow-hidden.

**Comment by davidtheclark** [comment]
A rotated square has size limitations — has to be a square. If that's ok, though, it has some other advantages — like, it could have box-shadow applied to it.

**Comment by davidtheclark** [comment]
Closed by #651.
