### ISSUE TITLE
Look into more sophisticated text underlining

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#222]
There was a whole pile of articles a year or two ago about how to make better text underline styles.  For example: https://eager.io/blog/smarter-link-underlines/  and https://medium.design/crafting-link-underlines-on-medium-7c03a9274f9

Main thing is to see if any of the options are flexible about background color.

cc: @katydecorah @tristen

**Comment by katydecorah** [comment]
Lil update: `text-decoration-skip: ink` is now available in Chrome 57. But not enough browser support to implement/open back up this ticket yet.
