### ISSUE TITLE
Clean up debug page, link to it from docs?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#348]
The debug page is helpful to illustrate every rule, but it's sloppy. I think we should make a call. Either clean up the debug page components so they're more systematic, and link into debug pages from core documentation, _or_ hide it from the nav and just keep it as a tool for developers who are working on Assembly. 

If we do decide to keep it, we should do a few things:

- Rebrand debug page to 'examples'
- Link to related sections of the debug pages from main documentation site. 
- Most things that have color or style variations should have a debug page

**Comment by davidtheclark** [comment]
I think we should remove Debug from the public docs, but still put the work into cleaning it up so we can use it to check our work.

**Comment by samanpwbb** [comment]
@davidtheclark I think this page has value for anyone. A simple pass consistifying the headings and clarifying the sections + removing some of the junk and we are good.

**Comment by davidtheclark** [comment]
🆗
