### ISSUE TITLE
Improving the Example Page

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#438]
Quick and dirty mockups of how we could treat the examples page:

![untitled 001](https://cloud.githubusercontent.com/assets/8495845/21443976/0e2ab6f2-c877-11e6-8300-1f86cdadb232.png)

<hr>

![untitled 002](https://cloud.githubusercontent.com/assets/8495845/21443981/17daf310-c877-11e6-8260-4fb46430b79b.png)

How does this relate to https://github.com/mapbox/assembly/issues/348?

@samanpwbb

**Comment by davidtheclark** [comment]
Per chat, let's ditch the example page, maybe putting one example on the home page.
