### ISSUE TITLE
Add a color reference page

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#462]
when all the classes are already listed in the examples?
<img width="969" alt="screen shot 2016-12-25 at 11 40 16 am" src="https://cloud.githubusercontent.com/assets/5186564/21472683/be913114-ca99-11e6-8757-96dd31917b58.png">

**Comment by dasulit** [comment]
We should make a color reference similar to the layout reference @davidtheclark made here: https://www.mapbox.com/assembly/layout-scales/

Updating title to reflect this!

**Comment by davidtheclark** [comment]
@lshig @jfurrow: This is an issue that one of you might consider taking on. It will give you a chance to tinker in this site's idiosyncratic build system and learn about Assembly.

**Comment by samanpwbb** [comment]
Closing: for now lets remove the 'show all' ui and keep color docs inline like everything else.
