### ISSUE TITLE
Blue background is slightly hard to read 

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#466]
white text on bright blue background is a bit hard to read

<img width="256" alt="screen shot 2016-12-25 at 11 12 15 am" src="https://cloud.githubusercontent.com/assets/5186564/21472705/49432754-ca9a-11e6-80d0-4263156ea6cd.png">

**Comment by mayagao** [comment]
No one seems to think this blue hurts eyes closing here

**Comment by davidtheclark** [comment]
I agree @mayagao! What color would you prefer.

**Comment by samanpwbb** [comment]
@mayagao  made some nice adjustments to style in https://github.com/mapbox/assembly/pull/468 – i can bring those back.
