### ISSUE TITLE
Bleed classes don't "meet the edge of the screen"

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#499]
The current description for bleed classes says:

> Bleed classes allow an element inside a centered container to escape the container and meet the edge of the screen

And right below that is an example where the element does not in fact reach the edge of the screen. What is it reaching to the edge of? What's really going on here?

**Comment by samanpwbb** [comment]
Bleed class is designed to only work inside centered limiters that have content flush to left and right of limiter.
