### ISSUE TITLE
Add dark link

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#502]
currently `link--gray-dark` does not work only `link--gray` works

**Comment by samanpwbb** [comment]
What should happen on hover in this case?

**Comment by davidtheclark** [comment]
Yeah, none of the `*-dark` colors should work for hoverable things. Forgot to document this. We should document it or come up with an alternative strategy (answer @samanpwbb's question).

**Comment by mayagao** [comment]
I think underline as hover state can work. or blue link

**Comment by samanpwbb** [comment]
You can make regular text blue on hover now with `color-blue-on-hover`. We could add a `txt-underline-on-hover` util as well.

**Comment by davidtheclark** [comment]
I will add this `txt-underline-on-hover` class of which you speak.
