### ISSUE TITLE
Another font size, 14, 13? 

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#509]
On brochure pages 12 and 10 are almost never used. and 15 is too big sometimes as body font for lots of texts (mostly documentations and for things like the pricing page where there used to have a four-column table with dense content). I'm trying 14 in the new ios doc https://www.mapbox.com/ios-sdk/api/3.4.0-beta.6/Geometry.html#/c:MGLGeometry.h@F@MGLRadiansFromDegrees. Seems like too many fonts sizes if we keep them.

Also not sure if this should be an issue here or a design decision we make when doing the custom version for mapbox.com

**Comment by samanpwbb** [comment]
Part of Assembly's mission is to be flexible to a point, but then to build in best practices for users. One way we do this is by maintaining only a limited set of font sizes.

Mapbox tends to use fonts that are too small, and we should kick this habit. We shouldn't just make this change on mapbox's mod of assembly, but build it into main assembly.

15px is already a little small for suggested body copy. There's a lot of evidence supporting using larger font sizes on web pages (rules for apps are and should be different). Some examples: https://www.smashingmagazine.com/2011/10/16-pixels-body-copy-anything-less-costly-mistake/, https://www.imarc.com/blog/best-font-size-for-any-device, http://pielot.org/2016/01/optimal-font-size-for-web-pages/

One thing we could do is make a set of coordinated changes to our typographic scale:

`.txt-l` and up: keep the same
`.txt-m` 👉  16px
`.txt-s` 👉  13px
Maybe add an 11px here (?)
`.txt-xs` keep the same

Note that the rules change when you're building interfaces. Small fonts are a necessity.

**Comment by mayagao** [comment]
I think 16/15 works for generic brochure pages but not documentations, dense tables, forms components ... the scale should be project specific so I guess we should close here

**Comment by samanpwbb** [comment]
I would like to find a way for us to _not_ have project specific scale, but one shared scale. I am not opposed to adjusting or adding another font size.

**Comment by samanpwbb** [comment]
Lets wait and see what people build and return to font scale if necessary!
