### ISSUE TITLE
Add negative margin rules

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#518]
Negative margins are generally useful, especially for absolute positioning and then offsetting things inside a relative-positioned container. 

I think I would use rules like `m-neg12`, `m-neg18`, and `m-neg24` pretty regularly if we had them.

**Comment by davidtheclark** [comment]
Here's [a comment I found](https://www.smashingmagazine.com/2009/07/the-definitive-guide-to-using-negative-margins/#comment-185564) about negative margins:

> I don’t know why people are so scared about using negative margins, when used correctly they can make a site look one hundred per cent better than it did

So yeah! Let's make sites one hundred per cent better.
