### ISSUE TITLE
Add `cursor: pointer` to `label` elements

### ISSUE THREAD

**Issue by kronick** [mapbox/assembly#519]
Right now if you have a group of radio buttons, checkboxes, or switches with label elements, there is no cursor-change hint that clicking the labels will toggle the associated element.

I am working around this with a simple rule:

    label {
         cursor: pointer;
    } 

Currently:
![toggle-nopointer](https://cloud.githubusercontent.com/assets/186834/21628911/40617b32-d1d8-11e6-8d8c-25a1defaf7b1.gif)

Desired:
![toggle](https://cloud.githubusercontent.com/assets/186834/21628915/445257f2-d1d8-11e6-9951-19d0f5a9e8ed.gif)

**Comment by samanpwbb** [comment]
You _could_ use the cursor-pointer class for this: https://github.com/mapbox/assembly/blob/f183d16e421c0254aaa2c9f4c24aa681b05a4e82/src/theming.css#L241

However, quick google search suggests UX best practice is to use a pointer cursor here: http://ux.stackexchange.com/questions/23266/should-the-cursor-change-to-pointer-over-radio-buttons-checkboxes-their-labels

I would be in favor of hadding cursor: pointer to containers: https://github.com/mapbox/assembly/blob/f183d16e421c0254aaa2c9f4c24aa681b05a4e82/src/forms.css#L502-L507
