### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#521]
Let's think about how this will be versioned. 

Right now we are recommending that people use `mapbox.com/assembly/assembly.css`. That will be the version of the stylesheet on the live site. But if there are breaking changes, then, other projects will break without warning or a chance to opt-out of the update. So I don't think it's a good system.

We could suggest people use [unpkg](https://unpkg.com/#/) and publish the `dist/` built files as part of the npm package (though not committed to the repo).

If we want a Mapboxier method for deployment, we should deploy versions to S3, right? Then serve them from there.

We also need a changelog.

**Comment by samanpwbb** [comment]
Ugh yeah we we definitely need a versioned URL. How does Mapbox gl js do it? Ideally we can copy them.

**Comment by tristen** [comment]
re-opening. Unfortunately the way I have it now:

```
https://mapbox.com/assembly/v0.1.0/assembly.min.css
```

won't work as publisher removes everything in the directory and replaces it with the output of `npm run build`. We'll need to save this to a different bucket that's not subject to this.
