### ISSUE TITLE
fade-in, fade-out, and shake examples are useless

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#536]
By the time you get to these, they have already run their course and illustrate nothing. Maybe the best we can do is add a note that this is the case and encourage the user to refresh their browser at that scroll position?

**Comment by dasulit** [comment]
Replay button?

**Comment by tristen** [comment]
infinite should be a modifier?

**Comment by davidtheclark** [comment]
> infinite should be a modifier?

That sounds like a good idea to me! For all the animations.
