### ISSUE TITLE
Select options are bold in (desktop) Safari

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#537]
![screen shot 2017-01-04 at 10 00 14 am](https://cloud.githubusercontent.com/assets/628431/21651119/aadc4884-d264-11e6-81ce-be478c35d339.png)

They might also be bold in some other browsers, I'm not sure if I paid attention to that.

We should reset those to normal font-weight.

**Comment by dasulit** [comment]
Unfortunately, just `.select option { font-weight: normal }` doesn't override this. I tried to look around to see how selects are treated elsewhere, and it seems like select options either a) accept the font-weight and size of the select in Safari; or b) more commonly, aren't bold..

**Comment by davidtheclark** [comment]
Closed in favor of #565.
