### ISSUE TITLE
Allow horizontal scroll in .pre blocks

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#538]
Otherwise we end up with madness like this:

![screen shot 2017-01-04 at 10 02 14 am](https://cloud.githubusercontent.com/assets/628431/21651182/e77838fc-d264-11e6-9cdb-9daa9cd6bee8.png)

**Comment by samanpwbb** [comment]
should we just `overflow: auto` on all `.pre` and `.prose pre`?

**Comment by davidtheclark** [comment]
@samanpwbb Yeah, that's my plan.
