### ISSUE TITLE
On mobile Safari, date input is not same width as other inputs

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#540]
![image](https://cloud.githubusercontent.com/assets/628431/21651667/be0d5612-d266-11e6-99da-fbf8ee3a6181.png)

**Comment by davidtheclark** [comment]
As far as I can tell, the only way to fix this would be to set `display: block; width: 100%` on `.input` elements. In which case we'd want to do the same thing on `.textarea` elements.

This is a significant change, but I'm not opposed to it — kind of leaned that way earlier on but didn't say anything. The justification would be that we are forcing the user to deliberately decide on an input width, either by assigning a width class or wrapping the input in a container that determines its width. The browser default widths are definitely inconsistent in this case, maybe also in other cases.

Alternately, we could just warn people not to use `type="date"` inputs, and maybe prevent any styling from being applied to `type="date"` inputs.

Thoughts?

**Comment by samanpwbb** [comment]
@davidtheclark i agree with you about 100%'ing inputs and textareas.
