### ISSUE TITLE
Circle-stroke icon

### ISSUE THREAD

**Issue by tmcw** [mapbox/assembly#546]
I'd like to make a UI like

![image](https://cloud.githubusercontent.com/assets/32314/21657318/b1c01560-d28f-11e6-9063-ff097060ee56.png)

I could fake this with radio elements, but would rather stay truer to the DOM and use icons. Could there be an unfilled circle icon in assembly?

**Comment by samanpwbb** [comment]
To do this, I recommend using width and height classes, plus border and fill classes, plus `round-full`.

So like:

```html
<!-- doesn't have a stroke -->
<div className='round-full p3 border border--2 border--transparent'>
    <div className='round-full w6 h6 fill-blue'/>
</div>

<!-- has a stroke -->
<div className='round-full p3 border border--2 border--blue'>
    <div className='round-full w6 h6 fill-blue'/>
</div>
```
