### ISSUE TITLE
Maybe add a flex-child class

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#548]
After realizing #547, I thought I'd run through all the [documented flexbugs](https://github.com/philipwalton/flexbugs) and see if any others might bite users of our utility classes.

I think we're in pretty good shape, given the limited scope of our flexbox classes. I think two changes might help us avoid these bugs (pretty much *in IE11 only*):

- Add a `flex-child` class. It *kind* of sucks to do this, but it wouldn't be too bad. Usually things will work fine *without* applying this class to children; but it might save us sometimes. This would also involve changing the existing `flex-child-*` class to be modifiers: `flex-child--*`. This class would have just a few bug-avoiding declarations:
  - `flex-shrink: 0;` (re https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored)
  - `flex-basis: auto;` (re https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored)
  - `max-width: 100%;` (re https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container)
  - `display: block;` (re https://github.com/philipwalton/flexbugs#12-inline-elements-are-not-treated-as-flex-items)
- Remove any usage of the `flex` shorthand (re https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed)

Anybody have any concerns about these changes?

**Comment by samanpwbb** [comment]
@davidtheclark this makes sense to add if we want to actually support IE11.
