### ISSUE TITLE
Sizing things up

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#553]
Re #328, we're thinking about making the released version include all color variants. I think this makes sense from the perspective of easy documentation & easy usability, but I also feel a little wary of committing so many bytes by default to things that might not get used often — for example, range inputs.

So I did some size experiments to see what % of filesize is dedicated to what things. Here's what I got:

**Current**
205 kB (minified) => 23.4 kB (gzipped)

**Without ranges**
171 kB (minified) => 20.5 kB (gzipped)

**Without ranges, switches, toggles**
152 kB (minified) => 18.5 kB (gzipped)

**Without ranges, switches, toggles at all; checkbox, radio, select, input, texture color variants**
122 kB (minified) => 15.4 kB (gzipped)

**So ...**
- Ranges are 12.4% of the gzipped file size.
- Ranges, switches, and toggles combined are 20.1% of the gzipped file size.

It's clear that those numbers are drastically disproportionate to the amount of use those components will get. 3.1 kB and 4.9kB are pretty small numbers, though. So maybe we needn't worry about the disparity.

If these numbers do bug us, though, here's a possibility: We could package the work we've done on those components into separate JS libraries, where you feed in a standard and dark color as variables and some CSS is generated and put into the page at runtime. The libraries themselves would be extremely tiny, and the CSS they generate would also be tiny, because focused on only the color variants that get used. Thoughts?

**Comment by samanpwbb** [comment]
> If these numbers do bug us, though, here's a possibility: We could package the work we've done on those components into separate JS libraries, where you feed in a standard and dark color as variables and some CSS is generated and put into the page at runtime. The libraries themselves would be extremely tiny, and the CSS they generate would also be tiny, because focused on only the color variants that get used. Thoughts?

Has the flexibility we want without the weight. I worry that this would move a lot of configuration burden onto designers who just want things to work, though. If we can do this in a way that has a very simple, streamlined API, I'm all for it!

**Comment by davidtheclark** [comment]
Let me try to sketch out an API that might work:

```js
MapboxAssembly.generateRangeInput({
  primaryColor: '#fff',
  darkColor: '#eee',
  className: 'my-range' // defaults to .range
});
```

As long as you run that somewhere, you should be able to use the class name `my-range` on any `input type="range"` and have it styled fancy.

**Comment by samanpwbb** [comment]
@davidtheclark what about something like this:

```js
MapboxAssembly.generate({
  components: ['range', 'button'],
  colors: ['white', 'blue']
});
```

Where there's a config file with all the colors as part of the library. It's a little heavier,  but it's more convenient.

**Comment by davidtheclark** [comment]
Interesting idea. I think these are probably just ideas we can keep in mind as we get feedback.

(I doubt there are any noticeable performance implications of adding such a small amount of CSS at runtime instead of loading it via a cached stylesheet.)

**Comment by davidtheclark** [comment]
Let's close this for now, revisit later based on feedback & ideas.
