### ISSUE TITLE
Default form elements color should not be blue

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#554]
It's fine the default button color is blue, but other form elements like text inputs, toggles should not be blue. Normally people would use some sort of gray on a white background, and blue border when in focus.

**Comment by samanpwbb** [comment]
I'd prefer if every form component had the same starting point. Think of the default states almost like 'unstyled' components. It's easy to customize inputs to be gray and then blue on active.

**Comment by samanpwbb** [comment]
I changed my mind – no real harm in providing good defaults – folks who want something custom will have to add modifier classes either way: https://github.com/mapbox/assembly/pull/556
