### ISSUE TITLE
Icon sizes are not at the same scale

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#563]
Some icons are clearly bigger than others:

<img width="124" alt="screen shot 2017-01-05 at 5 47 31 pm" src="https://cloud.githubusercontent.com/assets/5186564/21676109/63973590-d36f-11e6-895a-0169762abfb1.png">

**Comment by davidtheclark** [comment]
I think you might need to follow this up by naming specific icons to resize. They are all being rendered in the same way, so I believe the fix here is to adjust the SVGs.

**Comment by mayagao** [comment]
yeah i wonder if it would help to have a set padding inside this 18x18 container for all icons, assigning myself.

**Comment by samanpwbb** [comment]
tracking in https://github.com/mapbox/assembly/issues/966
