### ISSUE TITLE
Only way to avoid cross-browser uglinesses for select is JS

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#565]
#537, #525, #534 illustrate some cross-browser annoyances with our CSS-only styled selects. They are not vital problems, they just make the component a little uglier than we'd like in Firefox and IE.

I'm thinking the only way we could avoid such cross-browser uglinesses would be to provide JS power to the select component. Essentially, we want an overlay div displaying the chosen value, whose style we can control fully. We just need JS to update its value when the select changes. It might be a little tricky to make the same JS work on its own and in combination with React, but could be done.

I'm going to close those specific issues because they all point back to this one, where we can decide if a JS solution is worthwhile or not.

**Comment by samanpwbb** [comment]
> I'm thinking the only way we could avoid such cross-browser uglinesses would be to provide JS power to the select component.

Lots of other frameworks do this, and I think users expect to be able to style select options. If we can pull it off in a straightforward, will be great. See https://material-components-web.appspot.com/select.html or https://ux.mailchimp.com/patterns/forms#select-dijit for some precedents.

**Comment by tristen** [comment]
I am +1 for sticking with native selects. Styling issues might get better in the future (right? 🙃) and abandoning it for JS requires a lot of work. For instance on mobile

Native Select | JS Select
:---|:---
Streamlined for mobile. Selection is large clear and assessable. | There's no focus state, scrolling hides or makes it jump around, and it's position varies on the page.
![img_1818](https://cloud.githubusercontent.com/assets/61150/21906990/9ed7b028-d8db-11e6-818c-4fcd13bd5415.PNG) | ![img_1819](https://cloud.githubusercontent.com/assets/61150/21906991/9ed8b0ae-d8db-11e6-8869-758544a5a4ed.PNG)

---

Considering Assembly is _Mobile first CSS_ I think there's a strong case against having a JS solution.

**Comment by davidtheclark** [comment]
Nobody's proposing that we create a completely custom select here (like the second example), just that we use JS to tailor a controllable "facade" element that overlays the native select. So the native benefits (focus, positioning of menu, arrow keys, mobile thing, etc.) would all remain — like the first example, like we already have, but fixing the bugs mentioned above, which I do not think can be fixed well without JS intervention.

**Comment by davidtheclark** [comment]
The unfortunate hole in this plan is that `<select>` elements can & will be added to the page dynamically, so a script that runs on initialization will not catch them. We'd have to expose a function on a global variable that users would then have to call whenever they dynamically add a `<select>` element to the page. 

@samanpwbb and @tristen I misunderstood the comments above and realized @samanpwbb was actually considering the thing that @tristen did not want — a full JS select, including dropdown.

Because of the two issues above, I'm just going to quietly close this. If ideas strike us like lightning, we can return.

**Comment by samanpwbb** [comment]
Probably for the best 👍
