### ISSUE TITLE
Increase paragraph font size in prose?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#569]
Prose text is too small in a lot of cases. Options:

- Just make .prose p and related elements font sizes larger
- Add the prose-big modifier like we had in base.
- Increase default font size across the board. Go to like 16px/30px or so.

**Comment by tristen** [comment]
> Increase default font size across the board. Go to like 16px/30px or so.

My vote ^

**Comment by mayagao** [comment]
I don't think we should increase font size across the board since brochure pages have slightly complicated layout and 15 seems to be a nice balance between readability and elegance. 

> Adding a prose-big modifier

👍

**Comment by tristen** [comment]
> Adding a prose-big modifier

If we do that, I think it should be a modifier added to the mapbox add-on. It would be nice to keep a uniform type scale in default assembly.
