### ISSUE TITLE
sidebar vertical spacing is off in safari

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#573]
<img width="241" alt="screen shot 2017-01-05 at 7 37 39 pm" src="https://cloud.githubusercontent.com/assets/108094/21703213/6eff4f26-d37e-11e6-851b-74cd53b46821.png">

**Comment by dasulit** [comment]
the container of the logo needs to have a min-height, I fixed this earlier but looks like it got reverted. https://github.com/mapbox/assembly/pull/557
