### ISSUE TITLE
IE11 button text descends on click

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#580]
This is ripe:

![jan-06-2017 16-33-39](https://cloud.githubusercontent.com/assets/628431/21736439/f0f7846c-d42d-11e6-80ee-f0c21190faad.gif)

Do we want to try to kill that behavior?

**Comment by davidtheclark** [comment]
@mayagao After searching around about this, it seems that the only way to fix it is to add a child with `position: relative` wrapping the button's contents. I do not think that this detail is worth addressing.

**Comment by mayagao** [comment]
🙇🏿
