### ISSUE TITLE
Syntax error in webpack config

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#585]
@tmcw Are you on Node >4 or am I doing something wrong? When I tried `npm run start` I got a syntax error because the webpack config uses the spread operator in this pattern `...!isDebug ? [] : [`.

Probably we should make this build work on Node 4, in line with other Mapbox things, right? If so, I can put together a PR replacing this pattern.

**Comment by tmcw** [comment]
Yeah, sorry - I was on Node v7 when I was testing that. Will downgrade my default and accept any PR.

**Comment by tmcw** [comment]
🤔 also shouldn't this issue be in a different repo?

**Comment by davidtheclark** [comment]
Agh, whoops.
