### ISSUE TITLE
Not possible to float icon inside text input

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#590]
In this input + icon example I want to center position an absolute positioned icon 

<img width="1069" alt="screen shot 2017-01-09 at 5 10 55 pm" src="https://cloud.githubusercontent.com/assets/61150/21786190/c008dd82-d690-11e6-8bc5-5bf887eec4c8.png">

For a 36px height input a top margin of 9px and left padding of 36px for the input works. I _could_ try a different technique by absolute positioning a 36x36 container and centering an icon within it but that requires more markup to do. could we increase the position scales to:

- Increment by 3px until 12px
- Increment by 12px until 48px
- Increment by 24px until 96px

cc @samanpwbb @davidtheclark

**Comment by samanpwbb** [comment]
can you vertical center the icon with flexbox? I think when the intention is to vertically center something, it's better to use a flexible centering technique.

**Comment by davidtheclark** [comment]
![screen shot 2017-01-09 at 3 36 35 pm](https://cloud.githubusercontent.com/assets/628431/21786510/6d746e10-d681-11e6-834a-6bbb2b92cd76.png)

Are those class names state secrets?

**Comment by tristen** [comment]
ok ok ok

**Comment by tristen** [comment]
wellllllll actually the left padding on the input is still an issue.

**Comment by samanpwbb** [comment]
@tristen i renamed this issue to reflect the fundamental problem here. I think there are three options:

1. Add more padding rules.
  - 👍 Additional padding rules is the more flexible and simple option.
  - 👎  More padding rules means we maybe want to adjust our layout utility scale everywhere, so 

2. Add a new component called `input-with-icon` that had `input-with-icon--s` and `icon-with-icon--r` modifiers. This modifier would be used on a wrapping div around an icon and an input. 
  - 👍  Adds fewer total classes.
  - 👎  Adds a rule that is not just a simple single-class selector.
  - 👎  New component is a new component – an entirely new class of rules in assembly. We are trying to avoid these, not good for usability.

3. Do not suggest that people follow this pattern. It goes against the grain of the web – faking a child in an element that can't have children. If people want to implement this pattern, they can use inline left-padding or write their own class.

I think there are good arguments for and against both options but I lean slightly towards option 1.

**Comment by davidtheclark** [comment]
Here's the markup I like for that pattern:

```html
<div class="relative">
  <div class="absolute top bottom left flex-parent flex-parent--center-cross pl6">
    <svg class="icon"><use xlink:href="#icon-search"></use></svg>
  </div>
  <input class="input input--border-teal w180 pl30" placeholder="teal">
</div>
```

The gives us real vertical centering with flexbox. The trouble is that there's no `pl30` class :(

**Comment by tristen** [comment]
Definitely into option 1. I don't think we should introduce a built-in assembly component and I don't think we can expect people to not want to create something like this.

**Comment by davidtheclark** [comment]
> Increment by 12px until 48px

Does not give me my 30px.

How do we decide? Where will it end?!

**Comment by tristen** [comment]
You're joking @davidtheclark but I don't think adding `36px` to our positioning classes is unreasonable. The height of most input elements equals this.

**Comment by davidtheclark** [comment]
@tristen I'm confused as to what `36px` is for. I need `30px`. I thought you needed `9px`. I'm not being coy, really. There has to be some justification for when we decide not to include some padding value, right? Do we want to increase linearly by 6 up to some point so we have `30px`?

**Comment by tristen** [comment]
> @tristen I'm confused as to what 36px is for

If I want to pin a container to the left of an input element that contains a center aligned icon like this:

<img width="1271" alt="screen shot 2017-01-09 at 7 53 28 pm" src="https://cloud.githubusercontent.com/assets/61150/21789800/a80ddb14-d6a5-11e6-9b3a-90b4aa4df815.png">

`36px` would be great! It equals the height of the input and I can add a `.pl36` so it exactly clears the width and height of the container. Not arguing the case for not adding 30px but I think _Increment by 12px until 48px_ is just a simple and reasonable change.

**Comment by davidtheclark** [comment]
Ah, that's your left padding. Just means a little more padding on the horizontal axis than what I had. I like that it equals the height. Makes sense.

**Comment by samanpwbb** [comment]
These extra padding rules make sense to me as well lets so it  👍

**Comment by tristen** [comment]
We good with ^. closin!
