### ISSUE TITLE
Document the logic for layout sizings in docs

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#592]
Possibly under the **6px baseline grid** heading within _Overview_. I looked and I don't think we document anywhere how layout utility classes increment. Something like:

>Increment by 3px from 0 until 6px
Increment by 6px until 12px
Increment by 12px until 48px
Increment by 24px until 96px

Also touch on the inclusion of negative values and higher margin values

**Comment by samanpwbb** [comment]
same as https://github.com/mapbox/assembly/issues/551 right?

**Comment by tristen** [comment]
whoops! yes!
