### ISSUE TITLE
.{property}-{color}-on-active.is-active should override hover rules

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#596]
That's a crazy long classname but for the hover state of active elements that have a different style than it's siblings:

![on-hover-is-active](https://cloud.githubusercontent.com/assets/61150/21823583/a70049b0-d749-11e6-8695-d77c87caa582.gif)

**Comment by samanpwbb** [comment]
This seems unnecessary. `is-active-{*}` should default to having the same state on hover. I think we just need to re-order some CSS to make this work correctly.

**Comment by tristen** [comment]
Yikes. You're right. Adjusting the title
