### ISSUE TITLE
Custom scrollbars

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#60]
We probably want these 🙈

**Comment by davidtheclark** [comment]
@samanpwbb @tristen @mayagao Have any of you ever run into problems with the current framework's custom scrollbars? If not, should we essentially copy those styles over, with minor tweaks?

**Comment by samanpwbb** [comment]
Base's scrollbars are bland, and too narrow. We should try to design some fresh scrollbars. 

I have been avoiding this issue because good custom scrollbars are hard to pull off, and whenever I've tried to design generic custom scrollbars, I end up overriding them in specific projects. Also: only Webkit support.
