### ISSUE TITLE
Remove `link-*` classes

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#602]
It wasn't until I re-read the docs that I came across `link-*` again. Like it was [cited here](https://github.com/mapbox/assembly/issues/458#issuecomment-269403390) I am 👍 on removing them. You can virtually re-create the same effect (minus hover darkening) using utility classes and I think it's something that should only be added to Assembly until the squeeze is too great not to have it.

**Comment by davidtheclark** [comment]
Why should it be removed? To save file size? Does it introduce some cognitive dissonance that bothers you? I just don't understand what new motivation prompts this, after we've already discussed it plenty. 

To repeat the main reasons we wanted *not* to rely on utility classes:

- Ensure consistent color variation — links always darken on hover, they don't lighten, they don't stay the same color.
- Ensure consistent hover states — @samanpwbb will testify that if we don't include a hover state, many people won't reliably do so on their own.

I'm happy to leave this entirely in the hands of @samanpwbb. I don't want to talk about it again, though, either way.

**Comment by tristen** [comment]
> Why should it be removed? To save file size? 

Not everything is file size with me. We should remove it because the use case is not strong enough to keep it and It's a weird component, (not quite `txt-` not quite `color-*`) and a thing `color-*` classes _could_ provide.

> Ensure consistent hover states — @samanpwbb will testify that if we don't include a hover state, many people won't reliably do so on their own.

A user is still required to know about `link-*` and add it. How do you know people will reliably use it? Aren't you just trading one thing for the other?

**Comment by samanpwbb** [comment]
Link classes make a lot of sense. Let me break down how they make sense and follow existing patterns in Assembly.

> You can virtually re-create the same effect (minus hover darkening) using utility classes

Compare them to the `btn` class. `btn` can be re-created with utility classes: `round bg-blue bg-blue-dark-on-hover bg-blue-dark-on-active px12 py6`. Links can be recreated with `color-blue color-blue-dark-on-hover color-blue-dark-on-active`. The reason we provide component classes in addition to utility classes is to _make it easier to follow UX conventions_ (darken on hover, and on active) and to provide nice defaults (`link` class is blue by default, as are buttons).

If Assembly were a different kind of framework, with different principles, we would have neither a `btn` class nor a `link` class. The `link` class is part of Assembly's goal of being pragmatic, convenient, and encouraging good UX.

> And now everything needs to be duplicated `link--{color}` when I can also do `link color-{color}`

A rule like `.link.color-blue:hover {...}` violates class declaration patterns in Assembly: it add a side-effect, and it adds a rule with more specificity than necessary. Utility classes should never have different behavior when used alongside a component class.

> A user is still required to know about link-* and add it. 

This is true for every class in every CSS framework. I don't understand how this is a valid argument.

---

All that said, the `link` class is optional (as is every class in every CSS framework). If you want to create your own links with `color-blue color-red-on-hover color-green-on-active`, there are no technical reasons why you can't do that.

**Comment by tristen** [comment]
Alright I'm going to close. I guess this all comes back to my complaints with components which I'm on the losing end of the argument of.
