### ISSUE TITLE
If the value is a pixel name it in the class

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#605]
Our positioning classes established a naming convention where we spell out the pixel value it corresponds to (e.g. `.p24`). There's a couple places where we don't keep to this convention:

- `.round`
- `.round-bold`
- `.shadow-bold-*`

`-bold` is vague. How bold is it? I think we should standardize to keep in line with positioning classes and still keep descriptive words (like `full`, `half`) to refer to values that are percentage based.

**Comment by samanpwbb** [comment]
Yes, I support this change for single-rule utility classes. 

I think we should keep the [`headline` to `xs`](https://github.com/mapbox/assembly/blob/227bc3403c6b1c3b080c55873b66ad5ddbfb8d00/src/typography.css#L46-L79) range for typography. We should also keep `s` to `xl` modifiers for things like loaders, triangles, icons, buttons and forms.

**Comment by davidtheclark** [comment]
Eeeeh ... I'm partly ok with this but partly not. The numeric scales exist on values for which you *must* pick one number of out of many, right? There is no "default" for width, padding, etc. However, for `round` and `shadow` it makes sense to have a default; and it's a little misleading to suggest, by analogy with the layout classes, that there is a wide range of values for you to choose from. Additionally, this forces users to remember the "default" (is that `round-4` or `round-3`?). I'd be much more interested in switching `round-bold` to `round-l` (for large), and keeping `round`, than using `round-4` and `round-8`, or whatever the numbers are.

**Comment by dasulit** [comment]
Agree with @davidtheclark— Assembly has definitely evolved away from the `-bold` suffix, but as David said, the `round` classes have a "default" that might be frustrating as a pixel value. I like the treatment of `-xs`, `-xl`, etc. but `-l` overlaps with our naming convention for "left" 😕

I believe we've voiced this before, but the class `round` itself is kind of un-Assembly, too.. maybe we could just own it and name the classes `round` and `rounder`? (not sure how this would translate to shadows, though..)

**Comment by davidtheclark** [comment]
> -l overlaps with our naming convention for "left"

We could avoid all ambiguities by spelling out all these words, maybe abbreviating "extra" as "x" since that's pretty cool. I know a certain person who would be pleased by this, whose name starts with a T and rhymes with "glom".

**Comment by samanpwbb** [comment]
- I don't like the `bold` suffix.
- We use numbers for some sets that have only a small number of options (for example, letter spacing and animation timing). I would be perfectly okay with doing the same for shadows and border radiuses.
- does this issue concern anything else besides shadows and border radiuses?

**Comment by tristen** [comment]
Maybe:

`.round` 👉  `.round-s`
`.round-bold` 👉  `.round-m`
`.round-full` 👉  `.round-l`
`.shadow-darken5` 👉  `.shadow-s-darken5`
`.shadow-darken5-bold` 👉  `.shadow-m-darken5`

--- 

That said:

> We use numbers for some sets that have only a small number of options (for example, letter spacing and animation timing). 

Considering ^ `.round4`, `.round8`, `.round-full` doesn't seem that bad! `.shadow` doesn't have a clean name however.

**Comment by samanpwbb** [comment]
> .round 👉 .round-s
> .round-bold 👉 .round-m
> .round-full 👉 .round-l
> .shadow-darken5 👉 .shadow-s-darken5
> .shadow-darken5-bold 👉 .shadow-m-darken5

This works for me 👍

**Comment by davidtheclark** [comment]
One more idea to consider: with if we just did `round`, `round-l` and `round-xl`? The reason for that is we'd have a default, `round`, that would almost always get used.

No?

**Comment by tristen** [comment]
> One more idea to consider: with if we just did `round`, `round-l` and `round-xl`? The reason for that is we'd have a default, `round`, that would almost always get used.

My only concern is that it doesn't quite follow naming conventions in place. And I think there would be some expectation `-m` and `-s` exists. Also, as @dasulit noted, the class`round` is kind of un-assembly too.

**Comment by tristen** [comment]
I was going to incorporate these name changes into https://github.com/mapbox/assembly/pull/623 but it didn't feel right to prepend `-s` to `round` or `shadow`.

I don't like the `-bold` suffix either so maybe there's a change to make there. This could also be total bikeshedding and I'm happy to close this 😞

**Comment by davidtheclark** [comment]
@tristen What are your thoughts now? Want to talk about it?
