### ISSUE TITLE
Gutters are adding right margin to the container

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#610]
At some point this broke

<img width="738" alt="screen shot 2017-01-11 at 4 26 46 pm" src="https://cloud.githubusercontent.com/assets/61150/21867170/ff33fb6e-d81a-11e6-87f2-5c60ac23ccfb.png">

**Comment by tristen** [comment]
Which seems to be caused by the addition of `width:100%` to `.grid` in https://github.com/mapbox/assembly/blame/mb-pages/src/layout.css#L31 cc @davidtheclark 


![gutter](https://cloud.githubusercontent.com/assets/61150/21870246/62114c24-d829-11e6-8657-6f92e7f155b4.gif)

**Comment by davidtheclark** [comment]
Hm ... I will try to recall the problem that `width: 100%` fixed ...

**Comment by davidtheclark** [comment]
30576b82047ae039b51293cb97098b762b2a67d6 adds it ... I think it may have been a relic of some iteration on my attempts to fix the homepage. But if I remove it, I don't see any problem. Let's remove it. Sorry!
