### ISSUE TITLE
Recommend a starting html template

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#614]
I appreciate this page in Base: https://www.mapbox.com/base/html/ – includes meta tags, links to dependencies, and other html requirements. 

How is this:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1,user-scalable=yes">
  <link rel="shortcut icon" href="/path/to/favicon" type="image/x-icon">
  <link href="https://api.mapbox.com/mapbox-assembly/v0.2.0/assembly.min.css" rel="stylesheet">
  <script async defer src="https://api.mapbox.com/mapbox-assembly/v0.2.0/assembly.js"></script>
</head>
<body>

</body>
</html>
```

Should the template have anything else (there are so many directions to go here, how opinionated should we get?). I would prefer to keep it simple.

**Comment by davidtheclark** [comment]
I've heard it expressed that the `lang` attribute on `<html>` is kind of important. That's the only thing I know to add.

**Comment by tristen** [comment]
I _think_ `user-scalable=yes` is default? I've seen:

```html
<meta name='viewport' content='initial-scale=1.0 maximum-scale=1.0'>
```

As a nice standard

**Comment by tristen** [comment]
Also can we please please please use single quotes.

**Comment by samanpwbb** [comment]
Done https://github.com/mapbox/assembly/pull/662
