### ISSUE TITLE
Refactor navigation code

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#628]
### We could switch to react-router

I'm pretty sure https://github.com/ReactTraining/react-router can be used to render static pages. It would save us from some of the messes here: https://github.com/mapbox/assembly/blob/3abf09d90918095a2ffa0eab4a8a2a14d8e07a3b/site/routes.js, https://github.com/mapbox/assembly/blob/3abf09d90918095a2ffa0eab4a8a2a14d8e07a3b/site/navigation.js

### We could completely separate the code for building the documentation-css nav from other navs

Documentation CSS gives us data with a certain structure. We're trying to convert all our data to that structure, and it adds complexity. We could try separating code for generating the documentation-css nav, from code for generating route-based nav.

**Comment by davidtheclark** [comment]
Another possibility to consider, or maybe not, would be to try [next.js](https://github.com/zeit/next.js) (or something similar) that might solve a lot of these problems for us via conventional patterns. Or maybe it would make things more complicated and create work. I dunno. Just an idea.

**Comment by samanpwbb** [comment]
This was done when porting assembly to batfish.
