### ISSUE TITLE
Prominently display the latest version number

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#636]
People need to know if the documentation they're looking at corresponds to the version they're using. I think maybe we should add the current version number in the top left, by the icon, or the bottom left, by the GitHub link.

**Comment by samanpwbb** [comment]
Right now the documentation site doesn't _use_ the CDN'd version of assembly, but rather, the one located at mapbox.com/assembly/assembly.css

**Comment by davidtheclark** [comment]
Yeah, this is kind of a problem. I guess it will be less of a problem as we stop adding new layout classes — the main annoyance I'm suffering is when the Layout Scales page says something exists that I'm not actually able to use.

**Comment by davidtheclark** [comment]
To clarify the concerns:

- The CSS that has generated the documentation can be more recent than the actual deployed CSS, leading to dissonance between the docs and what users are using.
- If I'm using an outdated version of Assembly, I have no way of knowing that. It just seems like the documentation is wrong. My old version might be missing classes that the docs say I can use; but nowhere do the docs say which version they represent.
