### ISSUE TITLE
Vertical grid gutters

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#638]
What do you ya'll think about adding modifier classes for vertical grid gutters?

A person often finds themselves wanting to make a layout like this:

![screen shot 2017-01-18 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/628431/22084434/5ba35058-dd8d-11e6-84f7-3e66c6bd5d95.png)

In these situations, a vertical gutter is as important as a horizontal gutter. I imagine we could implement it in a similar way, right?

Is this crazy?

**Comment by samanpwbb** [comment]
I am opposed. This is what bottom margins are for! Horizontal gutters can't be made with margin classes alone.

**Comment by davidtheclark** [comment]
Eh, I'm not attached, but also don't see how it's different from horizontal gutters. You *could* just apply left-margins to all the columns, right? But then you'd have to know which is the *first* column, just like here you'd have to know which row is your last row ...

**Comment by samanpwbb** [comment]
> You could just apply left-margins to all the columns, right?

Sadly, you can't do that because you will end up with columns that are not equal sizes, or have an extra gutter on the left or right edge. Otherwise, I would be in favor of removing the horizontal gutters too.

**Comment by davidtheclark** [comment]
Yep, same as with vertical gutters ... but nevermind.
