### ISSUE TITLE
simplify modal close button markup

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#648]
@tristen this seems unecessarily complex: https://github.com/mapbox/assembly/blob/32bdbb990aae95d9902052eeb1c9d71275dd4536/site/examples/modal.js#L9-L13

Why flexbox? Why the empty button element vs placing the positioning rules directly on the button element? There is a lot to unpack and understand on these five lines of html.

**Comment by tristen** [comment]
> Why flexbox

Flexbox is great for centering things on a page rather than absolute positioning and offsetting it's size with negative margin + 50% left or right spacing.

> Why the empty button element vs placing the positioning rules directly on the button element?

Blame it on a first take? ¯\_(ツ)_/¯ it should be on the button container.

**Comment by samanpwbb** [comment]
> Blame it on a first take?

Yep, definitely. I don't expect any of this stuff to be right on the first go around. The examples we have now are a great start.

 I think we can collapse the button into one of the other containers. I don't think you need the `flex-parent flex-parent--center-main` declaration here because the icon is just getting pinned to the top right: https://github.com/mapbox/assembly/blob/32bdbb990aae95d9902052eeb1c9d71275dd4536/site/examples/modal.js#L8

**Comment by tristen** [comment]
omg I missed the `flex-parent flex-parent--center-main`. yes. it shouldn't be there.
