### ISSUE TITLE
expander.js should use event delegation

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#661]
Instead of assigning a different event listener to each *See all* button, we should add one listener to the document and react only if the click is on a relevant button.

@dasulit Have you used this technique before? It's worth learning about — I'd be happy to chat with you about it. Or if you'd prefer I can do this in a PR myself.

**Comment by dasulit** [comment]
@davidtheclark I'll give it a try! I have not used event delegation before, but I can look into it and take a shot at a PR on Monday.
