### ISSUE TITLE
Could all classes support media queries?

### ISSUE THREAD

**Issue by tmcw** [mapbox/assembly#668]
I see in the documentation that some classes support -mm  style media queries. It looks like the exceptions are color classes, and maybe buttons. Is the space savings from having 10%'ish of the CSS API surface without media query restrictions worth the complexity incurred by having to check the documentation to see if the class you're using supports them?

**Comment by tristen** [comment]
yes it's worth that complexity. [Imagine this quadrupled](https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap).

**Comment by tmcw** [comment]
Okay, I guess there's that. I'm kind of confused by that file:

* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L8804
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L8823
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L9247
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L9598
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L10077
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L10740
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L12696
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L14163
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L14288
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L14319
* https://github.com/mapbox/assembly/blob/mb-pages/test/__snapshots__/build-color-variants.jest.js.snap#L14346

Why are there so many classes that all equate to `color: #72C781;`?

**Comment by davidtheclark** [comment]
@tmcw Each of those classes also has other effects. For example, `select--stroke-green-light` also shows up in the following rules:

```css
.select--stroke-green-light + .select-arrow {
  border-top-color: #72C781;
}
.select--stroke-green-light:hover {
  color: #01aa46;
}
.select--stroke-green-light:hover + .select-arrow {
  border-top-color: #01aa46;
}
```

None of those effects come with just using `color-green-light`.
