### ISSUE TITLE
Toggles should not have extra padding by default

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#673]
Right now toggles by default have a padding of `6px` all the way around. I'm thinking maybe we shouldn't have this. 

I'd bet toggles are more frequently used as standalone UI components than form controls, so I think the height does not need to match inputs.

Also, the x-padding means that when you don't have a border you will have to override the padding to get horizontal alignment with other things on the page.

<img width="343" alt="screen shot 2017-01-24 at 12 39 29 pm" src="https://cloud.githubusercontent.com/assets/628431/22263591/34369062-e232-11e6-84ad-cbe7b31cc1a0.png">

**Comment by samanpwbb** [comment]
I hear what you are saying. There will be no way to align these little things to vertical baseline without the built-in padding. I would be fine removing the padding, but it will cause similar problems for other cases, like when you are trying to correctly center a toggle inside a form element:

![screen shot 2017-01-24 at 2 44 39 pm](https://cloud.githubusercontent.com/assets/108094/22263790/a8af6264-e243-11e6-8e21-238b7792aa48.png)

**Comment by davidtheclark** [comment]
@samanpwbb: That screenshot you posted won't be helped by the padding, right? You'd need to vertically center. Regarding the vertical baseline, though, I'm happy to defer to what you want, and I can override padding with utility classes as needed.

**Comment by samanpwbb** [comment]
I am indecisive. I see benefits to both. Could we remove the padding by default, and add it only for stroked toggles?
