### ISSUE TITLE
Add all flex directions

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#689]
Which would be:

- `flex-parent--row` (The direction `flex-parent` gives us by default)
- `flex-parent--row-reverse`
- `flex-parent--column` (Currently the only direction variation in Assembly)
- `flex-parent--column-reverse`

Reverse is great for scenarios where your markup structure looks like:

```html
<container>
 <sidebar />
 <map />
</container>
```

And nn desktop you want the order to be sidebar/map and on mobile map/sidebar:

<img width="433" alt="screen shot 2017-01-26 at 12 04 06 pm" src="https://cloud.githubusercontent.com/assets/61150/22341708/dab8e604-e3bf-11e6-8e70-9faa7989c49a.png">

**Comment by davidtheclark** [comment]
@tristen Want to add these before today's release? Maybe wait for #679 to merge to avoid conflicts, then go for it.
