### ISSUE TITLE
txt-mono doesn't play well with txt-{scales}

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#694]
I've noticed that the font-size: 90% rule on `txt-mono` fights the font-size rules on `txt-s`, `txt-xs`, etc. when paired together.

![txt-mono-bug](https://cloud.githubusercontent.com/assets/8495845/22380260/d43f7c9a-e48a-11e6-89ac-5624db167f08.gif)

**Comment by samanpwbb** [comment]
This is a trick situation 🤔  – I have been placing `txt-mono` inside `txt-{size}`. The idea here is that monoweight fonts have very different proportions and need to be scaled down to match open sans. We could:

1. Keep things as-is
2. Switch rule order so `txt-{size}` rules override `txt-mono`.
3. Accept that monoweight fonts just have different proportions and are larger and remove the font-sze downscaling.
4. Add rules for `txt-{size}.txt-mono` that ensure `txt-mono` is always scaled down correctly even when used alongside `txt-{size}`

I vote for either 2 or 3. 4 introduces the kind of pattern we're trying to avoid in assembly.

**Comment by davidtheclark** [comment]
I vote for 2. If you are deliberately putting a `txt-{size}` class on the same element as `txt-mono`, that seems to be an indication that you really do want that `txt-{size}`.
