### ISSUE TITLE
Different version numbers in the documentation

### ISSUE THREAD

**Issue by ajithranka** [mapbox/assembly#698]
On https://www.mapbox.com/assembly/, the "Getting Started" and "HTML Template" sections mention different version numbers (highlighted in red).

<img width="790" alt="screen_shot_2017-01-30_at_11_37_43_am" src="https://cloud.githubusercontent.com/assets/11095038/22413806/da0a5ebc-e6e0-11e6-9513-befceaebfed9.png">

cc: @samanpwbb @davidtheclark

**Comment by davidtheclark** [comment]
Closed by #699.
