### ISSUE TITLE
Remove invisible borders from non-border buttons

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#701]
Right now, buttons have invisible borders: https://github.com/mapbox/assembly/blob/eafb67c644b973a6c650fff08bb01d370dfc4cd8/src/buttons.css#L32-L34

This is fine when you are using buttons unmodified, but if you are adding your own padding or text size classes to buttons, buttons get offset from pixel grid. 

I suggest we remove non-border buttons, adjust default padding, and then leave bordered-buttons the same as they are now (with borders, and with default padding adjustments to account for borders).

**Comment by davidtheclark** [comment]
@samanpwbb: One trick with this will be to make sure pills still work right — e.g. if the active state on a bunch of bordered-pills is to be filled with no border.

**Comment by samanpwbb** [comment]
> @samanpwbb: One trick with this will be to make sure pills still work right — e.g. if the active state on a bunch of bordered-pills is to be filled with no border.

As long as both are the same height by default, it shouldn't be a problem right? I can try to give this issue a shot later this week.
