### ISSUE TITLE
Do we need the mxl breakpoint?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#709]
We haven't used the mxl breakpoint anywhere yet on mapbox.com. Can we cut this? cc: @davidtheclark @mayagao

**Comment by davidtheclark** [comment]
I don't mind cutting it.

**Comment by davidtheclark** [comment]
@samanpwbb Sounds like this is back in your hands, since you've started waffling. I'm going to cut a release without making any breakpoint changes for now.

**Comment by davidtheclark** [comment]
I ran some numbers to see how many bytes we'd cut by removing the mxl breakpoint:

BEFORE: 244 kB (minified) => 28.3 kB (gzipped)
AFTER: 221 kB (minified) => 26.2 kB (gzipped)
~7% reduction in gzipped size

**Comment by samanpwbb** [comment]
I have been using this breakpoint frequently lately.
