### ISSUE TITLE
Multi-package magic? Ideas and questions!

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#713]
While using Assembly for a large React-Webpack project that shall remain nameless, I had some ideas. 

The React-Webpack Project wants to use icon SVGs directly as React components, rather than following the current prescription. Besides being a little more idiomatic and saving an HTTP request, this usage would offer the significant benefit that Webpack page bundles could include only the icons they need, without *ever* having to download *all* of the Assembly icons at once. 

So I says to myself, "Hey, maybe you should make an `assembly-react-icons` package that depends on Assembly, compiles the icon SVGs into React components, and exposes those components." This would be nice, but cause two problems:

- One more package to update and release when Assembly updates and releases. Boo.
- The focus-styling JS is not now consumable by other means, independent of the icon-SVG JS. In theory, [focus-ring.js](https://github.com/mapbox/assembly/blob/dev-pages/src/js/focus-ring.js) *could* be its own little npm package, useful to The General Public not just Assembly users.

After thinking the two thoughts above, I thought a third: Maybe this Assembly repo should become a monorepo! That way we could publish all of these packages without adding maintenance and release burdens:

- `assembly` itself, with its custom builds and all its files.
- `assembly-react-icons`, exposing React components for the icons.
- `shy-focus` (or some other name), exposing the `focus-ring.js` code.

**Comment by samanpwbb** [comment]
I think it makes sense to move in this direction eventually, but the amount of pain Assembly icons are causing us is really not so bad right now, and the trade-off is increased complexity, both for us maintainers and for users.
