### ISSUE TITLE
Media query classes not overriding like they should

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#718]
Problem: If I apply `flex-parent none-mm` to an element, it never actually gets `display: none`. The reason is that in our CSS `none` and its media variants are all above `flex-parent` and its media variants. So any `flex-parent` class will always trump any `none` class.

I believe that the way to get this right is to *make media-query classes always override non-media0-query classes*. The only way I can think of to accomplish this is to move media query classes to the bottoms of stylesheets. We could do this ourselves or use a PostCSS plugin to automate it. My inclination is to do it manually, because then we are knowingly manipulating the source order of the output.

**Comment by samanpwbb** [comment]
I 100% agree that we should move all media query classes to the bottom of the stylesheet.
