### ISSUE TITLE
Faster animation classes

### ISSUE THREAD

**Issue by kronick** [mapbox/assembly#721]
I really like the inclusion of animation classes for making an element fade in after some action without using jQuery. The only problem is the provided animation classes are too slow for most UI changes.

In addition to classes like `.animation--speed-1`, I would love faster animation timings, perhaps at jQuery's named values of 200ms (fast), 400ms (default), and 600ms (slow)

**Comment by samanpwbb** [comment]
> making an element fade in after some action without using jQuery.

I recommend using the `transition` class for fading elements in, instead of the animation classes.
