### ISSUE TITLE
Should it be possible to combine stroked and regular buttons in pills?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#722]
Right now, adding a regular button to a pill that includes a lot of stroked buttons results in this:

![screen shot 2017-02-16 at 11 57 30 am](https://cloud.githubusercontent.com/assets/108094/23031478/1c6d035c-f43f-11e6-84a6-265b3d95e55f.png)

See the 1px margin to the left of the second button? That is :no_good_man:. Fixing this in a way that keeps the class lists simple would likely be challenging.

**Comment by davidtheclark** [comment]
Yes, it should be possible. It *was* possible in the past. Some change to pills must have broken this.
