### ISSUE TITLE
hover state is broken on `btn btn--stroke` if on `a` element

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#725]
Our reset causes problems for `<a href='...' class='btn btn---stroke'>Button</a>` because of https://github.com/mapbox/assembly/blob/22adf098b31267eda204d156a1a0c857e97b68e7/src/reset.css#L77-L79

Options for fixing:

- Add explicit box-shadow to `.btn--stroke:hover`. 
- Add `:not(.btn--hover)` to the reset.
- Remove the reset (This seems like a weird rule to have in the reset?)?

**Comment by davidtheclark** [comment]
@samanpwbb I think you may have put it in there as part of an earlier attempt to make focus-outlines work but not overlap with hover. I think we should remove it.
