### ISSUE TITLE
txt-l should have a 'headline' variant with smaller line height

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#731]
This is a `txt-l txt-bold`, attempting to use it as a headline:

<img width="407" alt="screen shot 2017-02-24 at 12 00 26 am" src="https://cloud.githubusercontent.com/assets/108094/23295241/5474c592-fa24-11e6-8d9c-66433f0c6e2b.png">

It would look better like this, with tighter line height::

<img width="398" alt="screen shot 2017-02-24 at 12 00 22 am" src="https://cloud.githubusercontent.com/assets/108094/23295251/664ba4fc-fa24-11e6-81c0-3a2bff55150c.png">

We could add line-height modifier classes, or have separate 'body' and 'heading' typography classes, where 'heading' classes would have less line-height

**Comment by tristen** [comment]
line-height modifier classes sounds like the easiest approach.

> or have separate 'body' and 'heading' typography classes

I like this idea but I think it starts to blur how `.prose` is used a little?

**Comment by davidtheclark** [comment]
I think it depends on how control you want over the vertical rhythm. Utility classes would be fine but would allow bad decisions. Modifier classes would enforce acceptable variations for each size.
