### ISSUE TITLE
add mx-neg{#} ?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#743]
We have `ml-neg6` but no `mx-neg6`. Negative margins on both sides are sometimes useful:

![2017-03-01 18_41_11](https://cloud.githubusercontent.com/assets/108094/23486703/9fb8ecec-feaf-11e6-9fb5-8c6e49d6eb95.gif)

**Comment by davidtheclark** [comment]
Oh, I missed this one for the latest release. We should definitely add it to the next release.
