### ISSUE TITLE
Reconsider active checkbox style

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#745]
Active checkbox should have a filled background and a white checkmark, closer to the native checkbox style:

<img width="435" alt="screen shot 2017-03-04 at 5 07 36 pm" src="https://cloud.githubusercontent.com/assets/108094/23582653/333621f2-00fd-11e7-9509-79a04e8f2fc5.png">

**Comment by davidtheclark** [comment]
Fine by me. If everybody's on board, I'm happy to implement this next week.

**Comment by samanpwbb** [comment]
closed by #787
