### ISSUE TITLE
don't store entire SVG data in assembly.js

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#748]
assembly.js is 49kb / 15kb gzipped. That's pretty big. Most of the weight is in the form of SVG. We store full contents of every icon in assembly.js. This is unnecessary.

Let's look at the source code for one of these icons. This is the 'airplane' icon:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<svg viewBox="0 0 18 18">
  <path d="M7,4l1.6,4H5.5c0,0-1.4-2-2.5-2H2.2L3,8l1,3h4.6L7,15h2l3.2-4H14c1,0,2-0.7,2-1.5S15,8,14,8h-1.8L9,4H7z"/>
</svg>
```

Every icon is identical, except for the value of the `d` property on path. Rather than storing full SVG strings, we could store an object with the name of the icon and the path string:

```js
{
  ...
  airplane: "M7,4l1.6,4H5.5c0,0-1.4-2-2.5-2H2.2L3,8l1,3h4.6L7,15h2l3.2-4H14c1,0,2-0.7,2-1.5S15,8,14,8h-1.8L9,4H7z"
  ...
};

```

Then, we'd have a little function that runs client side, that takes object, maps it to an SVG document template, and uses that to build the actual SVG sprite.

Questions:

- Would the process of building the SVG sprite be slow / noticeable to users if we it on the client?
- Since a lot of the data we'd be removing here is the same for each icon, would the size savings actually not be that significant (doesn't gzipping do a pretty good job collapsing redundant data)?

**Comment by davidtheclark** [comment]
Keep in mind the size comparisons are against the `<symbol>` elements that end up in the big string, *not* the original `<svg>`s. Those symbols are already pretty simplified. A couple of examples:

```svg
<symbol id="icon-airplane" viewBox="0 0 18 18"><path d="M7 4l1.6 4H5.5S4.1 6 3 6h-.8L3 8l1 3h4.6L7 15h2l3.2-4H14c1 0 2-.7 2-1.5S15 8 14 8h-1.8L9 4H7z"/></symbol>
```

```svg
<symbol id="icon-alert" viewBox="0 0 18 18"><path d="M9 3c-.6 0-1.2.3-1.5.8L3.2 13c-.5.8 0 2 1.1 2h9.4c1.1 0 1.6-1.2 1.1-2l-4.3-9.2C10.2 3.3 9.6 3 9 3zm0 3c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1s-1-.4-1-1V7c0-.6.4-1 1-1zm0 5c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1z"/></symbol>
```

I guess we'd still cut a significant number of characters by removing the entire `<symbol ...>` and `</symbol>` parts.

> Would the process of building the SVG sprite be slow / noticeable to users if we it on the client?

I seriously doubt it.

> Since a lot of the data we'd be removing here is the same for each icon, would the size savings actually not be that significant (doesn't gzipping do a pretty good job collapsing redundant data)?

No way to know but by trying, I guess.

**Comment by davidtheclark** [comment]
As part of this effort, we should ensure that the ordering of the SVGs is *deterministic*. This can be important to checking whether the file *actually* changed (in substance) or not.

**Comment by samanpwbb** [comment]
Meh. Not worth it. Lets solve this from another angle: https://github.com/mapbox/assembly/issues/782
