### ISSUE TITLE
percentage based margins shouldn't be col modifiers

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#754]
% based margins have general utility outside of making empty column cells in the grid. We should adjust the way these rules are named: https://github.com/mapbox/assembly/blob/f5b024a2d712d5ba02d1f398cec7f508c2a084bc/src/layout.css#L64-L75

what about `offset{number}`?

**Comment by davidtheclark** [comment]
I don't think I understand. What's an example of the general utility outside of a grid?

And were you thinking `offset66` (the percentage)? Or `offset8` (the offset)?

If we want percentage margins outside the grid, should they just be new margin classes? Like `m66pct`?

**Comment by samanpwbb** [comment]
> What's an example of the general utility outside of a grid?

Adjusting positioning of an absolute positioned element. In fact, it's often useful to use % based widths on absolute positioned elements as well. I don't think grid width _or_ col rules should be modifiers.

> And were you thinking offset66 (the percentage)? Or offset8 (the offset)?

Either is fine. For consistency, switching to a naming scheme that uses the % value makes sense to me.

> If we want percentage margins outside the grid, should they just be new margin classes? Like m66pct

These rules would be identical to the in-grid classes though wouldn't they?

**Comment by davidtheclark** [comment]
> Adjusting positioning of an absolute positioned element. In fact, it's often useful to use % based widths on absolute positioned elements as well.

I guess I still don't really understand why this is more important than any number of other possible class sets we could add to Assembly. Examples aren't coming to mind where this is an important method. Also, why not create an absolutely positioned grid?

> I don't think grid width or col rules should be modifiers.

What is a "grid width" rule?

> For consistency, switching to a naming scheme that uses the % value makes sense to me.

Agreed. I think that also differentiates the purpose of percentage width and margin classes from grid classes. The former are utility classes so should fit the utility class conventions; the latter are component classes so can create their own conventions.

> These rules would be identical to the in-grid classes though wouldn't they?

If we were to add utility classes to achieve the same effects as some grid classes (e.g. `flex-child w33pct ml-5pct` to achieve something like `col col--4`), then the grid classes would only serve as convenient shorthands for styles that could be implemented in other ways. If we want to strongly encourage use of the grid, this seems like reason enough to keep the grid classes, even if the same effect *could* be implemented with utility classes.

**Comment by samanpwbb** [comment]
We don't need to do this.
