### ISSUE TITLE
Add base style tutorials to docs

### ISSUE THREAD

**Issue by amyleew** [mapbox/assembly#772]
The base tutorials like [two column page](https://www.mapbox.com/base/tutorials/two-column-page/), [single column list](https://www.mapbox.com/base/tutorials/single-column-list/), and [single page app](https://www.mapbox.com/base/tutorials/single-page-app/) were super helpful to getting starting with combing the different css elements in base. 

Can we duplicate those tutorials for assembly?

/cc @samanpwbb @tristen @davidtheclark

**Comment by samanpwbb** [comment]
There are already some layouts: https://www.mapbox.com/assembly/examples/. We can add more definitely!

**Comment by tristen** [comment]
Just noting that single page app examples are already here: https://www.mapbox.com/assembly/examples/sidebar-apps/ but we can definitely include two column page / single column list examples too

**Comment by amyleew** [comment]
sounds good!

**Comment by davidtheclark** [comment]
@lshig @jfurrow: Here's another issue to keep in mind as a way to familiarize yourself with Assembly.

**Comment by samanpwbb** [comment]
Closing as stale.
