### ISSUE TITLE
A more predictable grid system

### ISSUE THREAD

**Issue by mayagao** [mapbox/assembly#780]
This is more of a question than a feature request, but I would love to understand the rationale behind  the way our layout class system are defined: 

Margins, negative margins, paddings, width, max-widths all have a different scale system, 
they can increment based on a one-step, three-step, six-step, or 24-step scale. Negative margins stop at 24 but positive margins stop at 480. widths stop at 960 but max widths stop at 1600. 

This design makes the grid system less predictable and harder to use. Can someone explain to me why we are doing this or maybe even add the reasons to the documentation? 

![screen shot 2017-05-24 at 11 43 24 am](https://cloud.githubusercontent.com/assets/5186564/26412548/1ff2d090-4077-11e7-91a8-f556103d1561.png)

![screen shot 2017-05-24 at 11 55 32 am](https://cloud.githubusercontent.com/assets/5186564/26412803/eaffdbde-4077-11e7-9437-3431933f51e0.png)

cc @davidtheclark @samanpwbb @tristen

**Comment by samanpwbb** [comment]
The system is set up this way for practical reasons. Width, max-width, margin, padding are all different properties that are used in different ways, and do not need the same scale. 

I agree that the system can be frustrating. I'd be interested in alternatives that are more consistent but have fewer total classes. 

One option is 3 * 2<sup>x</sup>:

`3 - 6 - 12 - 24 - 48 - 96 - 192 - 384 - 768 - 1536`

Another option is 3 * 2<sup>x</sup> until 960, and then 3 * 2<sup>x</sup> * 10:

`3 - 6 - 12 - 24 - 48 - 96 - 30 - 60 - 120 - 240 - 480 - 960` (and then sneak in 1500 for limiter only)

We'd need to be more disciplined about how design layouts, but I think it would be possible to create almost any layout with just these values. If users wanted additional classes they would need to write custom CSS.

**Comment by samanpwbb** [comment]
Another option is to add a lot more classes! Maybe with the massive reduction in form component CSS that's coming with https://github.com/mapbox/assembly/issues/746, we can get away with this?

**Comment by mayagao** [comment]
I am in favor of a simpler scale system but more consistency across different categories.
