### ISSUE TITLE
A defense for faint gray-faint

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#791]
[This commit](https://github.com/mapbox/assembly/commit/11fc2205c3222467e9f9f85990b4c873e0b1322c) flew by weekend, and before Assembly 1.0 goes down I want to throw in a nitpicky defense for lightening up gray-faint again.

@samanpwbb your commit message reads "make faint gray legible"— can you say more about what you mean by legible? I don't think gray-faint should ever be used for text, but having an airy, almost-not-quite-white is really useful for backgrounds.

Here's what the new `#e5e5e5` looks like as the background for code snippets in the Assembly docs, where we're using `bg-gray-faint`... IMO this actually makes the text harder to read:

![screen shot 2017-06-06 at 4 14 49](https://user-images.githubusercontent.com/8495845/26850260-dad778b8-4ad4-11e7-855d-d28ce3d20402.png)

Maybe we could delete `color-X-faint` classes, maybe we could add a `almost-not-quite-white` class, maybe we could find a happy middle ground gray. I know this seems minor, and there were so many good changes in the weight loss program, I do use `bg-gray-faint` a lot though!

**Comment by samanpwbb** [comment]
I agree. It's too dark for how it's being used. On lower-quality monitors it'll be illegible if we make it fainter, but that shouldn't cause serious problems. 

How do you feel about shifting it down to rgba(0,0,0,.05) / #f2f2f2 from rgba(0,0,0,.1) / #e8e8e8?

**Comment by dasulit** [comment]
I would be happy with `#f2f2f2` 👍

**Comment by samanpwbb** [comment]
@dasulit assigned this to you!
