### ISSUE TITLE
unprose?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#793]
Kind of a weird idea, but maybe it is actually a good one ...

I'm thinking about situations when you're writing long prose *and* you want to intersperse special stuff inside it (e.g. UI components, custom-styled links and headings, a button, etc.). Example:

```html
<div class="prose">
  <h1>Title</h1>
  <p>Here is my <strong>prose</strong>.</p>
  <h2 class="txt-underline txt-s">Special-styled heading</h2>
  <p>I want this to be a special-styled link: <a href="place" class="bg-blue color-red">go to place</a>.</p>
  <div class="mt24">
    <a href="other-place" class="btn">Button link!</a>
  </div>
  <p>Here is more <em>prose</em>.</p>
</div>
```

The way that `prose` currently works, you would need to do one of two things:
- Ensure that you override all the `prose` styling you want to. This might be ok much of the time, but sometimes Assembly might not have the right classes for such overriding, and it ends up putting you in a slightly ambiguous situation: the class list no longer clearly explains why the element looks the way it does.
- Divide the prose block into pieces, so you don't end up with your special stuff wrapped in `prose`.

```html
<div class="prose">
  <h1>Title</h1>
  <p>Here is my <strong>prose</strong>.</p>
</div>
<h2 class="txt-underline txt-s">Special-styled heading</h2>
<div class="prose">
  <p>I want this to be a special-styled link: <a href="place" class="bg-blue color-red">go to place</a>.</p>
</div>
<div class="mt24">
  <a href="other-place" class="btn">Button link!</a>
</div>
<div class="prose">
  <p>Here is more <em>prose</em>.</p>
</div>
```

Not only is that not ideal, it also doesn't fully work: the `go to place` link is still going to have to deal with `prose` styling on the link.

So, the idea is to provide an `unprose` class, and append to all `prose` element selectors a `:not` expression that excludes those. E.g. `.prose a:not(.unprose)`, `.prose h1:not(.unprose)`.

```html
<div class="prose">
  <h1>Title</h1>
  <p>Here is my <strong>prose</strong>.</p>
  <h2 class="unprose txt-underline txt-s">Special-styled heading</h2>
  <p>I want this to be a special-styled link: <a href="place" class="bg-blue color-red unprose">go to place</a>.</p>
  <div class="mt24">
    <a href="other-place" class="unprose btn">Button link!</a>
  </div>
  <p>Here is more <em>prose</em>.</p>
</div>
```

Do you think this would be useful?

**Comment by samanpwbb** [comment]
I'm fine with it 👍, yes! I think it would be useful.
