### ISSUE TITLE
Margins section on Layout page has typo

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#796]
![screen shot 2017-06-14 at 8 34 20 am](https://user-images.githubusercontent.com/628431/27141127-4e26e742-50dc-11e7-8a42-02e282784c04.png)

I believe this should have `ml{n}` `mr{n}` `mt{n}` `mb{n}` but no `m{n}`.

**Comment by davidtheclark** [comment]
@lshig: This would be a good issue for you to take on. It'll be an easy fix once you find what to change, and will give you a chance to learn more about this codebase.

**Comment by lshig** [comment]
@samanpwbb covered this issue in dev-pages in [#787](https://github.com/mapbox/assembly/pull/787) and [here](https://github.com/mapbox/assembly/commit/4831ad6625c40c760bd03fb328778d4481960490#diff-71efaa6d540785a912db7414a4c07949). We'll just need to merge dev-pages with mb-pages when ready.
