### ISSUE TITLE
Prose links don't have a hover state

### ISSUE THREAD

**Issue by katydecorah** [mapbox/assembly#797]
![image](https://user-images.githubusercontent.com/2180540/27239329-7950898c-529e-11e7-8657-849585386a24.png)

Just noticed that prose links do not have a hover state. Also, what do you all think about giving prose links a color such as blue? Right now they are the same color as the text.

**Comment by samanpwbb** [comment]
I'd be okay with this! We can use interactive variables: https://github.com/mapbox/assembly/blob/dev-pages/src/variables.json#L65-L66
