### ISSUE TITLE
Nothing in 0.14 changelog about layout scale changes

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#816]
0.14 includes a bunch of changes to the layout scales: https://github.com/mapbox/assembly/commit/1946422f86f344d71ccd3b15da0c348595d49dd0#diff-759c953ebbf2b1a9d86f29ef197f9e30. These are going to cause a lot of trouble for us if we aren't super careful about them when we upgrade. @samanpwbb can you document those?

**Comment by samanpwbb** [comment]
Yikes! Fix on the way.
