### ISSUE TITLE
Remove stroke on disabled stroked button?

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#837]
I'd like to propose a minor stylistic change to buttons. Currently, when a stroked button is disabled, the background grays out and the stroke fades:

![screen shot 2017-08-08 at 12 58 39 pm](https://user-images.githubusercontent.com/8495845/29084432-f54faad0-7c39-11e7-9961-e81aaee740c4.png)

I think the combination of a background class and the stroke is a little bit off, I would prefer that stroked buttons appear like the standard disabled Assembly button (to maintain dimensions, we'd achieve this with colored strokes):

![screen shot 2017-08-08 at 1 00 47 pm](https://user-images.githubusercontent.com/8495845/29084540-4f49663e-7c3a-11e7-8b87-e0da8475dd37.png)

Any objections or opinions on this?

**Comment by samanpwbb** [comment]
I like this change!
