### ISSUE TITLE
Bring back -light form elements?

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#848]
As part of the [Assembly weight loss program](https://github.com/mapbox/assembly/pull/787), we removed the option for `-light` and `-faint` form elements in order to encourage more accessible forms. I would like to open up the possibility that we bring back at least `-light` forms, and maybe `-faint` forms, to Assembly.

For such forms, we could default to the text color rather than white text for legibility. At the moment, you can theoretically assemble a light or faint Assembly `btn`, but you cannot do the same for more complex forms such as toggles.

@mapbox/frontend, is there opposition to renewing `-light` and `-faint` forms? Would it be helpful or reasonable to include these variations for _some_ forms, but not all? Can we do a size comparison to get a sense of the weight difference this change would make?

**Comment by davidtheclark** [comment]
A size comparison would be good information for this choice!

**Comment by samanpwbb** [comment]
I would prefer to avoid making this change. It'd likely add a lot of weight and complexity to the framework.

**Comment by jseppi** [comment]
Due to not having the `.select--stroke-gray-light` styling, it appears not possible to style a `select` element to look like the default `.input` styling, which looks a little jarring when inputs and (stroked) selects are used together:

![screen shot 2018-07-26 at 10 42 45 am](https://user-images.githubusercontent.com/697848/43272894-b5f666fc-90c0-11e8-8919-d778c24107b1.png)

**Comment by davidtheclark** [comment]
Good point, @jseppi. But I think we definitely do not want to make the select's *text* match the faint gray of the input borders. So we'd need a special style where the border color is lighter than the text.

**Comment by davidtheclark** [comment]
I tried re-styling selects in https://github.com/mapbox/assembly/pull/918

**Comment by samanpwbb** [comment]
closing for same reason as https://github.com/mapbox/assembly/issues/945
