### ISSUE TITLE
margin examples missing from documenation

### ISSUE THREAD

**Issue by rgdonohue** [mapbox/assembly#850]
It looks like the section using margin (`my18`, etc) are [missing from the documentation](https://www.mapbox.com/assembly/documentation/#Margins)? They were in there at one point, but now it looks like it just includes the negative margin classes:

![image](https://user-images.githubusercontent.com/1952205/30172024-cf2540fc-93b0-11e7-944f-8799dca52410.png)

**Comment by dasulit** [comment]
Hey @rgdonohue, looks like something's wrong with the doc site: that `See all` button should reveal the hidden classes, but something's broken. We'll look into it; in the meantime, you can also see all the available layout classes here: https://www.mapbox.com/assembly/layout-scales/

**Comment by samanpwbb** [comment]
Same as https://github.com/mapbox/assembly/issues/914, fixed by https://github.com/mapbox/assembly/pull/978
