### ISSUE TITLE
line height / txt-* class woes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#862]
There's an issue with "component" classes like form elements, button, icons. We've designed all these base component classes assuming assuming a default lineheight of 24px (which is the body default: https://github.com/mapbox/assembly/blob/54d22b64b7b3f0580de2d60b977bb2964957b01a/src/typography.css#L15).

When combining `.txt-{size}` classes with these elements, layouts don't end up looking right: button labels become un-centered, form elements take up the wrong amount of vertical space. The best way to solve the problem is to ensure all "component" style classes include a line-height rule that will override the `.txt-{size}` line height rule. We need to do take this approach because many component classes have built in top/bottom margin or padding that requires special line-height treatment to ensure alignment.

We're currently inconsistently applying line heights to form elements (see https://github.com/mapbox/assembly/blob/54d22b64b7b3f0580de2d60b977bb2964957b01a/src/buttons.css#L93 or https://github.com/mapbox/assembly/blob/54d22b64b7b3f0580de2d60b977bb2964957b01a/src/forms.css#L81) – we should do this everywhere.

I'm open to other approaches. We could go radically in the other direction and decouple line height from txt sizes and from form elements entirely. That would create problems of it's own though, and would require implementors to spend more time tweaking top/bottom margins and paddings of elements in order to ensure proper alignment (and would also require us to add more small-unit padding and margin classes like `px1`, `px2`, ect).

**Comment by davidtheclark** [comment]
I'm not sure those examples are "inconsistent" — but are instead different situations. For `.input`, line-height can be used to vertically center text in a way that is consistent across browsers, right? For `.btn--xs`, I don't know why that particular line-height is there but I'm betting it's for a very different purpose.

How much of this problem, do you think, is caused by the fact that nobody seems to want to use the default styles for these things? Everybody wants smaller stuff everywhere.

Maybe I'm not fluent enough in line-height stuff to know without experimenting what the tradeoffs might be for any given approach — but I'm having difficulty imagining how we could make all the things we want to vertically align do so without either (a) having defaults that we *use*, or (b) using flexbox as needed.

**Comment by samanpwbb** [comment]
> I'm not sure those examples are "inconsistent" — but are instead different situations. For .input, line-height can be used to vertically center text in a way that is consistent across browsers, right? 

Both these examples illustrate the same core problem: these two rules interact with `txt-{size}` classes in unexpected ways.

> For .btn--xs, I don't know why that particular line-height is there but I'm betting it's for a very different purpose.

The line-height is set here to make the button shorter. There's an assumption in this button rule that users won't combine `btn--{size}` classes with `txt-{size}` classes. That somehow, the button will always be in a context where the `body` font size is being applied. Based on my usage of Assembly / reading other folks Assembly code, txt-{size} classes are very frequently applied to parent elements, or applied directly on component elements. The problem here comes down to the fact that `txt-{size}` classes set both text size as well as line-height.

> How much of this problem, do you think, is caused by the fact that nobody seems to want to use the default styles for these things?

Deviating from defaults is part of the way Assembly is supposed to be used. It should be easy to tweak button text size or padding. No matter what we do, implementers will deviate from defaults: might as well build the system around that assumption.

**Comment by davidtheclark** [comment]
I guess I don't feel capable of imagining a better future 🙁

**Comment by samanpwbb** [comment]
Hm you don’t think some increased degree of specificity and opinionated styling for the {component} and {conponent}—{size} classes would both maintain flexibility and give users better results?

The more I think about it, the more it seems a certain degree of rigidity in the themability of our conponent classes would be fine.
