### ISSUE TITLE
Using media query variants with border classes results in unexpected colors

### ISSUE THREAD

**Issue by jfurrow** [mapbox/assembly#864]
When using `border-l-mm`, this property is applied: `border-left: 1px solid !important;` Because this is using shorthand syntax, it implicitly sets the `border-left-color` value to `initial`, which can't overriden by a `border-color` class (specifically `border--gray-light` in my example). Both classes are using `!important`, but `border--gray-light` class presumably comes before the `border-l-mm` class in the source.

One solution might be to change the `border-l` family of classes to specifically apply the `border-width` and `border-style`, though this would increase the file size. Or we could alter the source order. Any thoughts on this?

The class list I'm using is: `border-t border-t--0-mm border-l-mm border--gray-light`

And here's the result:
![screen shot 2017-10-03 at 11 18 49 am](https://user-images.githubusercontent.com/1134755/31141823-49bf826a-a82d-11e7-98d3-349b56fe66df.png)
![screen shot 2017-10-03 at 11 18 39 am](https://user-images.githubusercontent.com/1134755/31141824-49c49ebc-a82d-11e7-801e-ca050a84d3e8.png)

**Comment by davidtheclark** [comment]
> One solution might be to change the border-l family of classes to specifically apply the border-width and border-style

This sounds like the right solution to me. More shorthands, more problems, that's what I always say.
