### ISSUE TITLE
More discoverable docs about class naming convention

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#879]
Assembly has a pretty strict class naming convention. @jfurrow expressed that he often forgets it and has a little trouble finding docs about it. We should make sure the convention is clearly documented and discoverable. Right now it's sort of hidden deep in the home page, which is not a page that people will use for reference.

**Comment by jfurrow** [comment]
I just read the naming convention paragraph on the home page, I guess I hadn't read that far before 😬 . My bad!

I guess the main confusion for me is how _modifier_ is defined. Here are some class names that are confusing to me:
1. `blue` in  `color-blue` is not a modifier, but `blue` in `border--blue` is
2. `inline` in `flex-parent-inline` seems like a modifier
3. `on-active` and `on-hover` suffixes seem like modifiers

**Comment by davidtheclark** [comment]
"Modifier" classes always come *alongside* a more generic class. `color-blue` is not a modifier because it does not have to be used in combination with `color` (e.g. `color color-blue`). But `border--blue` is a modifier because it must be used in combination with `border` (e.g. `border border--blue`).

`flex-parent-inline` is an alternative to `flex-parent`, not a modifier of it. You shouldn't use the two together. Same goes for `border-t` and `border`.

And `color-blue-on-active` is for the same reason not a modifier class: it stands on its own, does not need to be used in combination with `color-blue`.

It maybe that "modifier" is too generic a term, and there's a more specific one we could substitute.

**Comment by jfurrow** [comment]
> "Modifier" classes always come alongside a more generic class.

This is definitely helpful, thanks!

**Comment by samanpwbb** [comment]
https://github.com/mapbox/assembly/pull/1003
