### ISSUE TITLE
Instructions about changing switch color no longer accurate

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#883]
> Change the color of the dot when inactive, the border when inactive, and the background when active with a switch--{color} modifier (*-dark colors are not available).

It sounds like that applies to a previous version when the dot and border were different colors.

**Comment by dasulit** [comment]
@davidtheclark, I think these instructions are still correct.. you can still separately modify the color of the dot and the border (or background when active). The example seems to be working as the docs describe:

<img width="312" alt="screen shot 2017-11-09 at 4 36 26 pm" src="https://user-images.githubusercontent.com/8495845/32630842-2b5710a2-c56c-11e7-82bb-6ac5699422e6.png">


Maybe I am misunderstanding, or maybe this ticket belongs in a different repo?

**Comment by davidtheclark** [comment]
Hm, I think I was just confused. Thanks, @dasulit.
