### ISSUE TITLE
Inputs shrunk 6px

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#884]
In 0.19, the input sizing wasn't just refactored to set line-heights and font-sizes more carefully: the inputs also shrunk 6 pixes, from 36px height to 30px height. Was this intentional?

Before:

<img width="303" alt="screen shot 2017-11-08 at 7 47 11 pm" src="https://user-images.githubusercontent.com/628431/32586029-bff414c6-c4bd-11e7-9e8d-c10cd91f3bc2.png">

After:

<img width="238" alt="screen shot 2017-11-08 at 7 47 08 pm" src="https://user-images.githubusercontent.com/628431/32586027-bfd4560e-c4bd-11e7-8526-0a8c70fee6a4.png">

**Comment by samanpwbb** [comment]
🤔  are you sure there isn't something else going on with padding in your example? See https://github.com/mapbox/assembly/blob/0.19.0/src/forms.css#L31-L40 and 
![screen shot 2017-11-09 at 11 33 02 am](https://user-images.githubusercontent.com/108094/32616990-c3ec44fc-c541-11e7-8888-226f33331e2a.png)

**Comment by davidtheclark** [comment]
O, looks like I'll need to move this issue to our internal input component.
