### ISSUE TITLE
Documentation site: source links are broken

### ISSUE THREAD

**Issue by dasulit** [mapbox/assembly#905]
At https://www.mapbox.com/assembly/documentation/, links to the source for each assembly class at are broken, instead landing at a 404 page.

Here's an example of a broken link:
https://github.com/mapbox/assembly/blob/0.21.2/src/typography.css#L551

**Comment by davidtheclark** [comment]
Ack, looks like I didn't make a tag in `mb-pages` for the latest release, `0.21.2`.

**Comment by davidtheclark** [comment]
Fixed!
