### ISSUE TITLE
Worth adding new build options?

### ISSUE THREAD

**Issue by elifitch** [mapbox/assembly#911]
Adding new build options, allowing folks to more easily configure especially layout classes (widths, heights, grid), I think would be the final thing unblocking Assembly from widespread use. Having our own defaults baked into the project is awesome, but with these things configurable, I simply wouldn't want to use any other CSS system for personal work or prototyping.

What would folks think about making those options available in advance of or along with the 1.0 release?

**Comment by davidtheclark** [comment]
@elifitch 👍 I don't think there's anything blocking us from adding more custom build options — unless, on a case-by-case basis, the addition of one might add a disconcerting amount of complexity to the codebase. We could work on these one-at-a-time, too. 

Stepping back to take a broader view, I'd be curious to hear how you'd summarize *the value of Assembly* for the user who ends up making a significantly customized build. What are the key features Assembly would provide that would leave you better off than if you wrote your own CSS? (I have my own ideas, but want to hear yours.)

**Comment by elifitch** [comment]
The value right now, is that if you work at mapbox, assembly is great to use for production projects since it's a reflection of the mapbox design system. For non-mapbox users, they might want different vertical rhythms, spacings, breakpoints and the like.

Right now there isn't a particularly configurable functional CSS framework, and so it gets shoehorned into the prototyping role. Cool to bang out UIs with quickly, but once it's time to apply a unique design ethos to the project, you have to change to something else. Atomic, Bass, Tachyons, they're all kind of bootstrappy in this regard. Assembly could fill that gap as the only (to my knowledge) flexible functional css system.

**Comment by davidtheclark** [comment]
@elifitch Thanks for articulating those thoughts!

I had a sort of relevant thought: I just posted a couple of PRs that update dependencies — and it got me thinking —— Maybe we should split out the build system itself from the standard-built CSS/JS, into distinct packages. One minor reason is that updates to the build system shouldn't *need* to translate to a new version of the CSS/JS. The reason more relevant to this discussion, though, is that it if we think the custom build system is a useful standalone feature, we could clarify its value by differentiating it from the standard-built set that is "Assembly".

**Comment by elifitch** [comment]
@davidtheclark I like this idea! Do you envision assembly staying as the generated CSS, configuration for a build process, and importing some new repo to generate the stylesheet based on that configuration? If so I feel like that could work nicely

**Comment by samanpwbb** [comment]
With the rise of tailwind I really don't think we're going to have too many external users of Assembly. It's convenient that Assembly is open source, and it's convenient that it's aligned with Mapbox's design systems, but right now we do not plan to prioritize wider adoption of the project.  Closing.
