### ISSUE TITLE
"See all" buttons do not work

### ISSUE THREAD

**Issue by jseppi** [mapbox/assembly#914]
The "See all" buttons on the documentation site do not trigger an expansion of the container that holds the class pills.

![the-buttons-they-do-nothing](https://user-images.githubusercontent.com/697848/42843375-886690a0-89d5-11e8-9da9-f348821107be.gif)

**Comment by davidtheclark** [comment]
@jseppi I'm not actually seeing this problem — those buttons seem to work ok. Can you still reproduce?

**Comment by jseppi** [comment]
Yes. Maybe it is just that there are no hidden pills (ie, the buttons shouldn't even be shown)?

![assembly-see-all-bug](https://user-images.githubusercontent.com/697848/43473258-45768788-94b5-11e8-881f-6aa4d4e743ee.gif)

**Comment by davidtheclark** [comment]
Ahhh, that makes sense.

**Comment by samanpwbb** [comment]
This is done, see https://github.com/mapbox/assembly/pull/978
