### ISSUE TITLE
Maybe switch from postcss-custom-properties to postcss-simple-vars

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#915]
Now that  browsers have started supporting custom properties, [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) has gotten kind of weird — and it may have been a mistake to use that plugin.

For some time still to come, we won't be able to rely on custom properties in the browsers we need to support. So we are just using the syntax for templating purposes. I also don't think our variables are the kind of values that we could or should change on the fly or get tricky with, in the way that real custom properties might support.

All that leads me to think that maybe we should switch syntaxes to Sass-style `$var`s with [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars). The advantages in my mind:

- We aren't confusing our needs with real custom properties. 
- If an Assembly consumer actually does want to use custom properties, they won't have to worry about clashing with Assembly.
- The same plugin can replace variables in media queries, or anywhere else — it's really a straightforward templating tool.

@mapbox/frontend any thoughts about this?

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/assembly/issues/972
