### ISSUE TITLE
Should default btn--stroke have a 2px border?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#916]
If we're defaulting to a 2px border for unfilled buttons, it would probably make sense to build that into Assembly's styling. The modifier class would be `btn--stroke--1`, then, to make the outline narrower if that's what you want.

@samanpwbb @tristen @dasulit what do you think?

We could also make the stroke 1px default if you apply `btn--s`.

**Comment by samanpwbb** [comment]
This is a good dilemma between pragmatism (we usually use 2px so lets make it default) vs conceptual consistency (`border` classes are 1px by default with 2px modifiers). I don't have a strong opinion either way but I lean _slightly_ toward preserving current behavior and using a react component to make btn--stroke--2 part of mapbox's default style.

**Comment by dasulit** [comment]
I think I personally lean towards "conceptual consistency". I would expect for button stroke to behave the same way as borders, and 1px as the border default makes sense.

Another thought.. I would be more comfortable making a 2px border button the default stroked button if we entirely eliminated the 1px version.

**Comment by samanpwbb** [comment]
> Another thought.. I would be more comfortable making a 2px border button the default stroked button if we entirely eliminated the 1px version.

Here's a spot where we'd need to make a change – maybe make a call on whether or not we're okay with this before committing. I'd be fine with dropping the 1x version:

![screen shot 2018-08-03 at 3 41 48 pm](https://user-images.githubusercontent.com/108094/43668827-d839884c-9733-11e8-8301-74c070f432f0.png)
![screen shot 2018-08-03 at 3 42 18 pm](https://user-images.githubusercontent.com/108094/43668828-d99eeb5a-9733-11e8-867c-e6caa6a16be2.png)

**Comment by davidtheclark** [comment]
Ok, let's just leave things as they are.
