### ISSUE TITLE
Revisiting borders and box-shadow-borders on inputs & selects

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#920]
In https://github.com/mapbox/assembly/pull/869 we switched from regular borders to box-shadow-borders with inputs and selects. The benefit was easier vertical-grid alignment. However, the downside is that it's harder to customize things — and the bug in this example illustrates that:

![2018-08-06 at 11 28 am](https://user-images.githubusercontent.com/628431/43734357-4c718d10-996c-11e8-9926-b59393a7d4cc.png)

`border-r--0` does not have the intended effect; there's no equivalent `box-shadow-r--0`, and there probably shouldn't need to be.

I suggest we try reintroducing borders to inputs & selects, adjust vertical padding to accommodate borders while matching the vertical grid.

**Comment by davidtheclark** [comment]
Ah, I realize now that one of the big benefits of box-shadow-borders is that they can remain grid-aligned *even if you use custom padding classes*.

If we used borders, instead, we could adjust the vertical padding to accommodate but only on the standard sizes: if you go add `py12` to your input it will end up 2px off the baseline grid.

**Comment by samanpwbb** [comment]
> Ah, I realize now that one of the big benefits of box-shadow-borders is that they can remain grid-aligned even if you use custom padding classes.
> 
> If we used borders, instead, we could adjust the vertical padding to accommodate but only on the standard sizes: if you go add py12 to your input it will end up 2px off the baseline grid.

Yeah, if we go back to borders, we should also discourage custom padding classes on inputs. I am ok with this as long as the predefined button classes support all the common formats across mapbox sites.

**Comment by davidtheclark** [comment]
Let's leave this as-is for now and see how far we get with it. If problems come up besides that hypothetical example, we'll consider a change.

**Comment by samanpwbb** [comment]
I'm going to close this, as a acceptable limitation to the system
