### ISSUE TITLE
CDN requests for v.26 returns 404

### ISSUE THREAD

**Issue by rgdonohue** [mapbox/assembly#960]
https://api.mapbox.com/mapbox-assembly/v0.26.0/assembly.min.css
https://api.mapbox.com/mapbox-assembly/v0.26.0/assembly.js

**Comment by BPHvZ** [comment]
@dereklieu

**Comment by tristen** [comment]
👋 thanks for the flag. Looks like deploying was skipped during the last couple of version bumps. These CDN requests should now be available.

**Comment by dereklieu** [comment]
Whoops. The docs are a little mysterious on this last point. Thanks @tristen.
