### ISSUE TITLE
Adjust color scale

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#961]
Assembly color scale has problems:
- some 'normal' colors are too low contrast against white and light backgrounds
- 'faint' and 'light' variants don't provide enough background shades for some apps. 'light' is too dark to use as a background shade in many cases.

Here's the proposal that adds two new shades to the color palette, a 'lighter', that provides another background shade, and a 'medium' that provides a high contrast shade that works on light backgrounds:

<img width="554" alt="Screen Shot 2021-02-24 at 11 52 10 AM" src="https://user-images.githubusercontent.com/108094/109057623-d1aed500-7696-11eb-9e18-55d89208f662.png">

These changes will be non-breaking, and will not effect form control generation in any significant way.

**Comment by samanpwbb** [comment]
@aparlato one thing to keep in mind as you start this work: We want base Assembly's palette to use  different colors from what we use internally in mbx assembly. The screenshot above covers mbx assembly. We should base then new lighter and medium shades on assembly's existing palette.

**Comment by tristen** [comment]
Can we scale back Assembly's default palette tremendously? Like 🪓 any purple, violet, yellow equivalents and just promote extending Assembly with BYOColors instead?

**Comment by samanpwbb** [comment]
I do think we still a good palette of colors for background and text (we could _maybe_ cut a color or two here), but agree about cutting down form, link, button colors from the default build!
