### ISSUE TITLE
Adjust typographic scale

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#962]
Right now assembly doesn't offer enough text contrast for dense UIs. We should add a new font size between txt-m and txt-s: txt-ms that is size 14 with line height of 21. Additionally, we should tweak txt-m to be 16px rather than 15px, which will normalize it's line height to 1.5 in addition to being a bit more legible. Here's the new scale:

**Comment by katydecorah** [comment]
@samanpwbb Do you imagine adjusting the heading font-size as well (looks like your original post didn't include the new scale)? The docs team has found that h1-h4 font-size are too large on content-based pages and I'm curious if other teams have the same feedback.

Here's a comparison of Assembly and Docs:

Selector | Assembly | Docs
---|---:|---:|
`.prose h1` | 45px | 36px
`.prose h2` | 35px | 30px
`.prose h3` | 30px | 24px
`.prose h4` | 18px | 22px


![image](https://user-images.githubusercontent.com/2180540/110660303-6afae280-8191-11eb-95cf-73c53b3fae66.png)

**Comment by samanpwbb** [comment]
@katydecorah I would be in support of adopting Docs team's scale in Studio and elsewhere. What line heights are you using? Also: for Studio, there are some cases where we'd want a "heading" style that is smaller than 18px. what do you think about an h5 class that is 16px/20?

**Comment by katydecorah** [comment]
> What line heights are you using?

@samanpwbb We are using the same line-heights as Assembly. It's possible we are being generous with whitespace so we'd be amendable to adjusting as needed.

> what do you think about an h5 class that is 16px/20?

Works for us! We are using Assembly's h5 right now.
