### ISSUE TITLE
Adjust shadow styles

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#964]
The current set of shadow styles apply shadows equally to all sides of an element. We should slightly offset our shadows on the y axis to imply elevation.

**Comment by samanpwbb** [comment]
There are two ways to implement this:
1. Add new offset shadow classes
2. Adjust existing shadows classes to add an offset. 

@katydecorah does docs rely anywhere on the symmetrical nature of our shadows or would approach (2) be acceptable? (2) would be great for the sake of simplicity.

**Comment by katydecorah** [comment]
@samanpwbb approach 2 will work for docs!
