### ISSUE TITLE
Consider adjustments to txt-spacing classes

### ISSUE THREAD

**Issue by katydecorah** [mapbox/assembly#967]
The docs team has found the `txt-spacing` classes to be too generous. We added the following class in the docs CSS to better match what we need. 

```
.txt-spacing0 {
  letter-spacing: 0.05em;
}
```

Have other teams run into this? I'm also curious if anyone uses `txt-spacing4`.

**Comment by samanpwbb** [comment]
@katydecorah Studio doesn't use any of these classes but I can pull this change into scope for the rest of the upcoming changes.
