### ISSUE TITLE
Make it easier to style borderless select elements

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#982]
We want to make it easier to add select elements that don't have borders and extra left and right padding:

<img width="464" alt="Screen Shot 2021-04-06 at 1 02 17 PM" src="https://user-images.githubusercontent.com/108094/113771532-55b59d00-96d8-11eb-808b-f4aa5e3cbf17.png">

Right now, to make borderless select elements that look good, some override classes need to be applied to get the spacing to look right. 

bordered and borderless selects should be managed with modifier classes.

**Comment by adrianababakanian** [comment]
👋 @samanpwbb can we close this now that the relevant PR was merged into the 1.0.0 branch, or should we wait until the release?

**Comment by samanpwbb** [comment]
@adrianababakanian let's close it now

**Comment by adrianababakanian** [comment]
Closed via https://github.com/mapbox/assembly/pull/992!
